import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Memories-social app</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
				<link rel='preconnect' href='https://fonts.gstatic.com' />
				<script
					src='https://kit.fontawesome.com/6aa24dfb93.js'
					crossorigin='anonymous'
				></script>
				<link
					href='https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Roboto&family=Playfair+Display:wght@900&family=Noto+Sans+JP&family=Encode+Sans:wght@300&display=swap'
					rel='stylesheet'
				></link>
			</Head>

			<main className={styles.main}>
				<h5 className={styles.title}>
					<a> Welcome to Memories- Social App!</a>
					<div>
						<br />
						<hr />
						<div className={styles.subtitle}>
							<Link href='/posts'>
								<a>Your Lovely Temple Memories</a>
							</Link>
						</div>
					</div>
				</h5>
			</main>
		</div>
	);
}
